import Head from "next/head";
import Script from "next/script";
import styles from "../styles/Home.module.css";
import Link from "next/link";


export default function Home() {
  return (
    <div className={styles.container}>
    
    
      <Head>
        <title>CoderHunts</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <nav className={styles.navbar}>
      <ul>
      <Link href="/">
     <a> <li>Home </li></a>
      </Link>
       <Link href="/about"><a ><li>About</li></a></Link>
       <Link href="/blogs"><a><li>Blogs</li></a></Link>
       <Link href="/contect"><a><li>Contect</li></a></Link>
       </ul>
      </nav>
      <Script src="/alert.js" strategy="lazyLoad"></Script>

      <main className={styles.main}>
        <h1 className={styles.title}><span > CoderHunts</span></h1>

        <p className={styles.description}>hunt the code by the CoderHunts</p>
        <div className="blogs">
        <div className="blogsItems">
        <h2>How to learn React in 2022</h2>
        <p>Learn react basic here from begining to advance level</p>
        </div>
        </div>
       

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
          </span>
        </a>
      </footer>
    </div>
  );
}
